name: driver_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.5.0

  http: ^1.2.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  firebase_database: ^12.1.4
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/bg.png" # untuk iOS
  adaptive_icon_background: "assets/icon/bg.png"
  adaptive_icon_foreground: "assets/icon/fg_driver.png"