// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7d6z6TGykKlQKobLAioAPt5OqUl3Sb20',
    appId: '1:441793358853:android:924c34007d08419b6dc06c',
    messagingSenderId: '441793358853',
    projectId: 'lacar-ekspedisi',
    databaseURL: 'https://lacar-ekspedisi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lacar-ekspedisi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQZAajFiChSa-XiCqOJZJcJSEgWOMFEM',
    appId: '1:441793358853:ios:cb9f4a2fe5efce296dc06c',
    messagingSenderId: '441793358853',
    projectId: 'lacar-ekspedisi',
    databaseURL: 'https://lacar-ekspedisi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lacar-ekspedisi.firebasestorage.app',
    iosBundleId: 'com.example.ekspedisiMobile',
  );

}